### ISSUE TITLE
Erreurs de code

### ISSUE THREAD

**Issue by EmmanuelBeziat** [Jissaii/knobyPlayer#1]
Il y a plusieurs variables derrières lesquelles il manque une virgule, le code plante.
Attention à ne pas laisser les console.log() trainer - ou bien tu peux utiliser créer une branche "develop" et les laisser dessus, mais cleaner pour publier sur master (qui est la version disponible au public).

**Comment by Jissaii** [comment]
J'ai changé normalement c'est bon, mais le code ne peut fonctionner que si tu as aussi le plugins : jquery.knob. Tu peux le trouver ici : https://github.com/aterrien/jQuery-Knob
